name: Build

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build